name: Deploy Application
on:
  push:
    branches:
      - main
  # pull_request:
  #   types:
  #     - opened
  #     - reopened
  #     - synchronize
  #     - closed
concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false
env:
  STAGE: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || (github.ref == 'refs/heads/main' && 'prod' || github.ref_name) }}
jobs:
  deploy:
    if: ${{ github.event.action != 'closed' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.3.6"
      - name: Install dependencies
        run: bun install

      # Staging
      - name: Create staging ./apps/server/.env
        if: github.event_name == 'pull_request'
        run: |
          touch ./apps/server/.env
          echo "BETTER_AUTH_SECRET=${{ secrets.BETTER_AUTH_SECRET }}" >> ./apps/server/.env
          echo "BETTER_AUTH_URL=https://trak-server-${{ format('pr-{0}', github.event.number) }}.eliot-153.workers.dev" >> ./apps/server/.env
          echo "BETTER_AUTH_PROD_URL=${{ vars.BETTER_AUTH_URL }}" >> ./apps/server/.env
          echo "CORS_ORIGIN=${{ vars.CORS_ORIGIN }}" >> ./apps/server/.env
          echo "CROSS_SUBDOMAIN_COOKIE_DOMAIN=trak-web-${{ format('pr-{0}', github.event.number) }}.eliot-153.workers.dev" >> ./apps/server/.env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> ./apps/server/.env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> ./apps/server/.env
      - name: Create staging ./apps/web/.env
        if: github.event_name == 'pull_request'
        run: |
          touch ./apps/web/.env
          echo "VITE_BETTER_AUTH_URL=https://trak-server-${{ format('pr-{0}', github.event.number) }}.eliot-153.workers.dev" >> ./apps/web/.env
          echo "VITE_SERVER_URL=https://trak-server-${{ format('pr-{0}', github.event.number) }}.eliot-153.workers.dev" >> ./apps/web/.env
          echo "VITE_WEB_URL=https://trak-web-${{ format('pr-{0}', github.event.number) }}.eliot-153.workers.dev" >> ./apps/web/.env

      # Production
      - name: Create prod ./apps/server/.env
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          touch ./apps/server/.env
          echo "BETTER_AUTH_SECRET=${{ secrets.BETTER_AUTH_SECRET }}" >> ./apps/server/.env
          echo "BETTER_AUTH_URL=${{ vars.BETTER_AUTH_URL }}" >> ./apps/server/.env
          echo "CORS_ORIGIN=${{ vars.CORS_ORIGIN }}" >> ./apps/server/.env
          echo "CROSS_SUBDOMAIN_COOKIE_DOMAIN=${{ vars.CROSS_SUBDOMAIN_COOKIE_DOMAIN }}" >> ./apps/server/.env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> ./apps/server/.env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> ./apps/server/.env
      - name: Create prod ./apps/web/.env
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          touch ./apps/web/.env
          echo "VITE_BETTER_AUTH_URL=${{ vars.BETTER_AUTH_URL }}" >> ./apps/web/.env
          echo "VITE_SERVER_URL=${{ vars.VITE_SERVER_URL }}" >> ./apps/web/.env
          echo "VITE_WEB_URL=${{ vars.VITE_WEB_URL }}" >> ./apps/web/.env

      - name: Deploy
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: bun run -F @trak/infra deploy --stage ${{ env.STAGE }}
        env:
          ALCHEMY_PASSWORD: ${{ secrets.ALCHEMY_PASSWORD }}
          ALCHEMY_STATE_TOKEN: ${{ secrets.ALCHEMY_STATE_TOKEN }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          PULL_REQUEST: ${{ github.event.number }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: true
  cleanup:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' }}
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Safety Check
        run: |-
          if [ "${{ env.STAGE }}" = "prod" ]; then
            echo "ERROR: Cannot destroy prod environment in cleanup job"
            exit 1
          fi
      - name: Destroy Preview Environment
        run: bun run -F @trak/infra destroy --stage ${{ env.STAGE }}
        env:
          ALCHEMY_PASSWORD: ${{ secrets.ALCHEMY_PASSWORD }}
          ALCHEMY_STATE_TOKEN: ${{ secrets.ALCHEMY_STATE_TOKEN }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          PULL_REQUEST: ${{ github.event.number }}
